// <auto-generated />
using AlertAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlertAPI.Migrations
{
    [DbContext(typeof(AlertAPIDBContext))]
    [Migration("20241126173311_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AlertAPI.Models.Alert", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("AlertAPI.Models.AlertIPAddress", b =>
                {
                    b.Property<int>("AlertID")
                        .HasColumnType("int");

                    b.Property<string>("IPString")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.HasKey("AlertID", "IPString");

                    b.HasIndex("IPString");

                    b.ToTable("AlertIPAddresses");
                });

            modelBuilder.Entity("AlertAPI.Models.IPAddress", b =>
                {
                    b.Property<string>("IPString")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Blacklisted")
                        .HasColumnType("bit");

                    b.Property<int>("sourceType")
                        .HasColumnType("int");

                    b.HasKey("IPString");

                    b.ToTable("IPAddresses");
                });

            modelBuilder.Entity("AlertAPI.Models.AlertIPAddress", b =>
                {
                    b.HasOne("AlertAPI.Models.Alert", "Alert")
                        .WithMany("AlertsIPAddresses")
                        .HasForeignKey("AlertID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlertAPI.Models.IPAddress", "IPAddress")
                        .WithMany("AlertsIPAddresses")
                        .HasForeignKey("IPString")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("IPAddress");
                });

            modelBuilder.Entity("AlertAPI.Models.Alert", b =>
                {
                    b.Navigation("AlertsIPAddresses");
                });

            modelBuilder.Entity("AlertAPI.Models.IPAddress", b =>
                {
                    b.Navigation("AlertsIPAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
